name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Metrics Left Pane
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-left-pane.svg
          plugin_achievements: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Metrics Right Pane
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-right-pane.svg
          base: ""
          config_order: music, steam, fortune
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_mode: recent
          # plugin_music_playlist: ${{ secrets.YOUTUBE_MUSIC_PLAYLIST }}
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}
          plugin_music_limit: 12
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_ID }}
          plugin_fortune: yes
          token: ${{ secrets.METRICS_TOKEN }}
